name: Publish Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Commit and push schema changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update dist
          file_pattern: dist
          branch: user.js
